### ISSUE TITLE
TypeError: protoBuf.loadProtoFile is not a function

### ISSUE THREAD

**Issue by luisnomad** [matrix-io/matrix-creator-malos#53]
I can't make any example work.

I have followed the instructions suggested here https://github.com/matrix-io/matrix-creator-malos/issues/33, like running 

`git submodule update --init`

and then `npm install` in the `src/js_test` folder, but it did not fix the issues for me.

I get this:

```
pi@raspberrypi:~/matrix-creator-malos/src/js_test $ node test_humidity.js 
/home/pi/matrix-creator-malos/src/js_test/test_humidity.js:22
var protoBuilder = protoBuf.loadProtoFile('../../protocol-buffers/malos/driver.proto')
                            ^

TypeError: protoBuf.loadProtoFile is not a function
    at Object.<anonymous> (/home/pi/matrix-creator-malos/src/js_test/test_humidity.js:22:29)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

**Comment by luisnomad** [comment]
I have run

`node`

then 

```
> var protoBuf = require("protobufjs")
> protoBuf.load
[Function: load]
> protoBuf.loadProtoFile
undefined
```

could it be that I need a specific version of protobufjs?

**Comment by luisnomad** [comment]
If I change `loadProtoFile` by `load`,  then I get:

```
/home/pi/matrix-creator-malos/src/js_test/test_humidity.js:24
var matrixMalosBuilder = protoBuilder.build("matrix_malos")
                                      ^

TypeError: protoBuilder.build is not a function
    at Object.<anonymous> (/home/pi/matrix-creator-malos/src/js_test/test_humidity.js:24:39)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

**Comment by brianofrokk3r** [comment]
Guys, found it, the latest version `protobufjs` has problems. 

The fix should be:
```
cd ~/matrix-creator-malos/src/js_test
npm install protobufjs@5.0.1 --save
node test_everloop.js
```

**Comment by luisnomad** [comment]
Thanks @brianofrokk3r, that fixes the issue!

**Comment by arhuaco** [comment]
I ran into the same issue. @brianofrokk3r 's workaround helped. 

I'm reopening the issue so that more people can see the workaround and because we haven't fixed it.

Two possible fixes:

1) Look into the API changes for v6.0 and update our examples.

2) Peg protbufjs version to the one that works (easy).

1 seems better for the long term.

**Comment by brianofrokk3r** [comment]
@arhuaco resolved?

**Comment by arhuaco** [comment]
npm installs protobufjs 5.0.2 so this is resolved.
